// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crtmgrz;

#nullable disable

namespace crtmgrz.Migrations
{
    [DbContext(typeof(CertificatesContext))]
    partial class CertificatesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("crtmgrz.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Authoritative")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificatePem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotAfter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotBefore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Pid")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrivateKeyPem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Pid");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("crtmgrz.Certificate", b =>
                {
                    b.HasOne("crtmgrz.Certificate", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("Pid");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("crtmgrz.Certificate", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
